//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApp.BankServiceProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankAccount", Namespace="http://schemas.datacontract.org/2004/07/ConceptArchitect.Banking")]
    [System.SerializableAttribute()]
    public partial class BankAccount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int accountNumberField;
        
        private double balanceField;
        
        private string nameField;
        
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int accountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                if ((this.accountNumberField.Equals(value) != true)) {
                    this.accountNumberField = value;
                    this.RaisePropertyChanged("accountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double balance {
            get {
                return this.balanceField;
            }
            set {
                if ((this.balanceField.Equals(value) != true)) {
                    this.balanceField = value;
                    this.RaisePropertyChanged("balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BankServiceProxy.IBankingCustomer")]
    public interface IBankingCustomer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingCustomer/Authenticate", ReplyAction="http://tempuri.org/IBankingCustomer/AuthenticateResponse")]
        string Authenticate(int accountNumber, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingCustomer/Authenticate", ReplyAction="http://tempuri.org/IBankingCustomer/AuthenticateResponse")]
        System.Threading.Tasks.Task<string> AuthenticateAsync(int accountNumber, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingCustomer/CloseAccount", ReplyAction="http://tempuri.org/IBankingCustomer/CloseAccountResponse")]
        double CloseAccount(int accountNumber, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingCustomer/CloseAccount", ReplyAction="http://tempuri.org/IBankingCustomer/CloseAccountResponse")]
        System.Threading.Tasks.Task<double> CloseAccountAsync(int accountNumber, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingCustomer/Transfer", ReplyAction="http://tempuri.org/IBankingCustomer/TransferResponse")]
        void Transfer(int source, int amount, string password, int target);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingCustomer/Transfer", ReplyAction="http://tempuri.org/IBankingCustomer/TransferResponse")]
        System.Threading.Tasks.Task TransferAsync(int source, int amount, string password, int target);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingCustomer/Withdraw", ReplyAction="http://tempuri.org/IBankingCustomer/WithdrawResponse")]
        void Withdraw(int accountNumber, double amount, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingCustomer/Withdraw", ReplyAction="http://tempuri.org/IBankingCustomer/WithdrawResponse")]
        System.Threading.Tasks.Task WithdrawAsync(int accountNumber, double amount, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingCustomer/Deposit", ReplyAction="http://tempuri.org/IBankingCustomer/DepositResponse")]
        void Deposit(int accountNumber, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingCustomer/Deposit", ReplyAction="http://tempuri.org/IBankingCustomer/DepositResponse")]
        System.Threading.Tasks.Task DepositAsync(int accountNumber, int amount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBankingCustomerChannel : BankApp.BankServiceProxy.IBankingCustomer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankingCustomerClient : System.ServiceModel.ClientBase<BankApp.BankServiceProxy.IBankingCustomer>, BankApp.BankServiceProxy.IBankingCustomer {
        
        public BankingCustomerClient() {
        }
        
        public BankingCustomerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankingCustomerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankingCustomerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankingCustomerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Authenticate(int accountNumber, string password) {
            return base.Channel.Authenticate(accountNumber, password);
        }
        
        public System.Threading.Tasks.Task<string> AuthenticateAsync(int accountNumber, string password) {
            return base.Channel.AuthenticateAsync(accountNumber, password);
        }
        
        public double CloseAccount(int accountNumber, string password) {
            return base.Channel.CloseAccount(accountNumber, password);
        }
        
        public System.Threading.Tasks.Task<double> CloseAccountAsync(int accountNumber, string password) {
            return base.Channel.CloseAccountAsync(accountNumber, password);
        }
        
        public void Transfer(int source, int amount, string password, int target) {
            base.Channel.Transfer(source, amount, password, target);
        }
        
        public System.Threading.Tasks.Task TransferAsync(int source, int amount, string password, int target) {
            return base.Channel.TransferAsync(source, amount, password, target);
        }
        
        public void Withdraw(int accountNumber, double amount, string password) {
            base.Channel.Withdraw(accountNumber, amount, password);
        }
        
        public System.Threading.Tasks.Task WithdrawAsync(int accountNumber, double amount, string password) {
            return base.Channel.WithdrawAsync(accountNumber, amount, password);
        }
        
        public void Deposit(int accountNumber, int amount) {
            base.Channel.Deposit(accountNumber, amount);
        }
        
        public System.Threading.Tasks.Task DepositAsync(int accountNumber, int amount) {
            return base.Channel.DepositAsync(accountNumber, amount);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BankServiceProxy.IBankingManager")]
    public interface IBankingManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingManager/GetAccount", ReplyAction="http://tempuri.org/IBankingManager/GetAccountResponse")]
        BankApp.BankServiceProxy.BankAccount GetAccount(int accountNumber, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingManager/GetAccount", ReplyAction="http://tempuri.org/IBankingManager/GetAccountResponse")]
        System.Threading.Tasks.Task<BankApp.BankServiceProxy.BankAccount> GetAccountAsync(int accountNumber, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingManager/CreditInterest", ReplyAction="http://tempuri.org/IBankingManager/CreditInterestResponse")]
        void CreditInterest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingManager/CreditInterest", ReplyAction="http://tempuri.org/IBankingManager/CreditInterestResponse")]
        System.Threading.Tasks.Task CreditInterestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingManager/OpenAccount", ReplyAction="http://tempuri.org/IBankingManager/OpenAccountResponse")]
        int OpenAccount(string customerName, string password, int amount, string accountType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingManager/OpenAccount", ReplyAction="http://tempuri.org/IBankingManager/OpenAccountResponse")]
        System.Threading.Tasks.Task<int> OpenAccountAsync(string customerName, string password, int amount, string accountType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingManager/GetAccountList", ReplyAction="http://tempuri.org/IBankingManager/GetAccountListResponse")]
        BankApp.BankServiceProxy.BankAccount[] GetAccountList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingManager/GetAccountList", ReplyAction="http://tempuri.org/IBankingManager/GetAccountListResponse")]
        System.Threading.Tasks.Task<BankApp.BankServiceProxy.BankAccount[]> GetAccountListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBankingManagerChannel : BankApp.BankServiceProxy.IBankingManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankingManagerClient : System.ServiceModel.ClientBase<BankApp.BankServiceProxy.IBankingManager>, BankApp.BankServiceProxy.IBankingManager {
        
        public BankingManagerClient() {
        }
        
        public BankingManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankingManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankingManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankingManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BankApp.BankServiceProxy.BankAccount GetAccount(int accountNumber, string password) {
            return base.Channel.GetAccount(accountNumber, password);
        }
        
        public System.Threading.Tasks.Task<BankApp.BankServiceProxy.BankAccount> GetAccountAsync(int accountNumber, string password) {
            return base.Channel.GetAccountAsync(accountNumber, password);
        }
        
        public void CreditInterest() {
            base.Channel.CreditInterest();
        }
        
        public System.Threading.Tasks.Task CreditInterestAsync() {
            return base.Channel.CreditInterestAsync();
        }
        
        public int OpenAccount(string customerName, string password, int amount, string accountType) {
            return base.Channel.OpenAccount(customerName, password, amount, accountType);
        }
        
        public System.Threading.Tasks.Task<int> OpenAccountAsync(string customerName, string password, int amount, string accountType) {
            return base.Channel.OpenAccountAsync(customerName, password, amount, accountType);
        }
        
        public BankApp.BankServiceProxy.BankAccount[] GetAccountList() {
            return base.Channel.GetAccountList();
        }
        
        public System.Threading.Tasks.Task<BankApp.BankServiceProxy.BankAccount[]> GetAccountListAsync() {
            return base.Channel.GetAccountListAsync();
        }
    }
}
